### ISSUE TITLE
No response after firmware updating

### ISSUE THREAD

**Issue by StopFxxkingCoding** [analogdevicesinc/study-watch-sdk#6]
After I used the Application WaveTool to update my watch firmware, the screen stopped at the display of **a tick icon √**, which meant the update was successful, I guess. But there was no more response after that, no matter I pressed two buttons in any way.

Is there anybody who could tell me how to make everything right? Or how to re-install the system when the watch has no response? @anoop-adi @nphilip-adi Thanks!

**Comment by anoop-adi** [comment]
Hi MaxandYuki,

Try to reset the watch by pressing the bottom navigation button (for 3 seconds).

Regards,
Anoop

**Comment by StopFxxkingCoding** [comment]
Hi Anoop,

Thanks for your reply! I have done that, but it didn't work. Also, I have tried several combinations of pressing buttons. But all cannot turn on/off the watch. Overall, the watch is out of response.

Best
Max

**Comment by anoop-adi** [comment]
Hi Max,

We can't replicate this issue on our side, so let us know the steps you followed, and info about the watch, Application WaveTool version, and how you were trying to update the firmware with BLE or USB.

Possible solutions: (you can try these options and then respond whether it worked or not for you)

1 - Try to connect the watch with a USB and see if you can see any COM port assigned to the device. (You can check it with ** Device Manager** > ports in windows )
2 - Try NRF connect app from the google play store (https://play.google.com/store/apps/details?id=no.nordicsemi.android.mcp&hl=en_IN&gl=US) and see if you can detect watch BLE on that APP. (NRF Connects scans for BLE devices)
3 - If none of the above methods work, its bootloader must be corrupted, but you can wait for the watch to discharge (It normally takes 24-48 hours for the watch to discharge) and then try to connect it with a USB for charging. (This should reset the watch)

If the watch is still not working, you need to update the bootloader using a Jlink. (I will send you detailed info about it once you confirm all the above 3 steps failed.)

Regards,
Anoop

**Comment by StopFxxkingCoding** [comment]
Hi Anoop,

Thank you for the detailed information provided in the last comment. Here, let me give more clues about the watch, software, and operations I went through. 

- **Watch**: From the guidebook, I think the version is **ADI VSM Watch IV**. The MCU is nRF52840And the ADI technologies used include ADPD4100, ADP5360, etc.
- **Software**: The software I used to perform the hardware update is WaveTool 5.0. After I encountered the problem, I also tried WaveTool 3.5. They both cannot solve it.
- **Operations**: The updating procedure is this: I used a USB cable to link the watch with my PC (with Win10). Then I successfully found the COM port and connected them. Then just followed the instructions in the guidebook to update the firmware. This process was smooth, and the progress bar in WaveTool was finished. However, after I disconnected the watch with PC, the watch screen only showed a tick icon. Whatever I do to it, there is no response. So I tried to totally discharge it (the details about this will be described later).

As for the three steps you aforementioned:

1. I link the watch with a PC using a USB cable. The WaveTool 5.0 can detect the port where the watch is mounted. But the connection failed.
2. Since I have no BLE dongle, I didn't try this connection method before. I have just now operated following your instruction in your comment step 2, the watch can be detected by Bluetooth using the APP nRF Connect.
3. I have tried to connect the watch via USB after the watch was discharged. Here some strange things happened. First, the screen showed some static horizontally organized snow dots, instead of the logo of ADI. Besides this, the WaveTool 5.0 USB connection can detect the port, but the connection result is failed and showed "Chip ID not detected - Please Reset the Device and Connect". And the screen froze at the display of those horizontal snow dots.

Best,
Max

**Comment by anoop-adi** [comment]
Hi Max,

Since you can get the COM port, so bootloader is fine. It looks like the firmware is not updated.

Few questions:
1 - Are you able to enter the bootloader mode?
2 - Have you tried to re-update the firmware?

Anyway, I think you should be able to access the watch using SDK. Can you try our python SDK and check if you can use the ADXL stream (getting started with python SDK: https://analogdevicesinc.github.io/study-watch-sdk/python/)

Regards,
Anoop

**Comment by StopFxxkingCoding** [comment]
Hi Anoop

Yes, the COM port and the Bluetooth signal are detectable. The problem is that I cannot communicate with the watch, either via the screen and the button or via the USB cable and WaveTool.

To answer your questions:
1. There is no response when I press buttons in any combinations. Consequently, I cannot enter the bootloader mode by pressing the select+navigate buttons.
2. Though the WaveTool can detect the COM port, the connection is failed all the time. So, I cannot carry out the update again.

Let me try to communicate with the watch using Python SDK. And the progress will be updated here later. Thank you for the help!

Best
Max

**Comment by StopFxxkingCoding** [comment]
Hi Anoop,

I have tested two example programs in the SDK reference doc, and the results are like the following:

1. Basic Example using USB
```
import time
from datetime import datetime
from adi_study_watch import SDK

# callback function to receive adxl data
def callback_data(data):
    sequence_number = data["payload"]["sequence_number"]
    for stream_data in data["payload"]["stream_data"]:
        dt_object = datetime.fromtimestamp(stream_data['timestamp'] / 1000)  # convert timestamp from ms to sec.
        print(f"seq :{sequence_number} timestamp: {dt_object} x,y,z :: ({stream_data['x']}, "
              f"{stream_data['y']}, {stream_data['z']})")


if __name__ == "__main__":
    sdk = SDK("COM4")
    application = sdk.get_adxl_application()
    application.set_callback(callback_data)

    # quickstart adxl stream
    application.start_sensor()
    application.enable_csv_logging("adxl.csv") # logging adxl data to csv file
    application.subscribe_stream()
    time.sleep(10)
    application.unsubscribe_stream()
    application.disable_csv_logging()
    application.stop_sensor()
```
The result is no output. I find that the function `callback_data()` is not called. This may be because the program didn't get any data from the watch.

2. How to log and download adxl stream data
```
from adi_study_watch import SDK
import time

# SDK setup
sdk = SDK("COM4")
adxl_application = sdk.get_adxl_application()
fs_application = sdk.get_fs_application()


# START LOGGING
adxl_application.start_sensor()
fs_application.subscribe_stream(fs_application.STREAM_ADXL)
fs_application.start_logging()
print(fs_application.get_status()["payload"]["status"])

print("logging...")
time.sleep(20)

# STOP LOGGING
adxl_application.stop_sensor()
fs_application.unsubscribe_stream(fs_application.STREAM_ADXL)
fs_application.stop_logging()
print(fs_application.get_status()["payload"]["status"])

# List all the files available to download.
files = fs_application.ls()
for x in files:
    print(x["payload"]["filename"])

# download data from the watch and save it to a file.
fs_application.download_file(files[0]["payload"]["filename"], download_to_file=True, display_progress=True)
```
The result of this program is error output, and the output print is like the following:
```
FSStatus.LOGGING_IN_PROGRESS
logging...
Traceback (most recent call last):

  File "...\temp.py", line 22, in <module>
    fs_application.stop_logging()

  File "...\adi_study_watch\application\fs_application.py", line 256, in stop_logging
    return self._send_packet(packet, FSCommand.STOP_LOGGING_RES)

  File "...\adi_study_watch\application\common_application.py", line 93, in _send_packet
    packet.decode_packet(response_byte)

  File "...\adi_study_watch\core\packets\fs_packets.py", line 447, in decode_packet
    self._packet["payload"]["stop_type"] = FSLogging(data[10:])

  File "...\enum.py", line 339, in __call__
    return cls.__new__(cls, value)

  File "...\enum.py", line 663, in __new__
    raise ve_exc

ValueError: [194] is not a valid FSLogging
```



From these tests, I feel that (1) the watch system perhaps got stuck, most likely during the loading procedure, so the SDK program cannot read data from the watch. (2) Or the system has not been updated successfully. Maybe something got wrong accidentally during the updating process. 

Best
Max

**Comment by anoop-adi** [comment]
Hi Max,

I have attached two examples; when you run these examples, it will create an **SDK.log** and **SDK1.log**, respectively. Can you send those logs?

```
from adi_study_watch import SDK

sdk = SDK("COM4", logging_filename="SDK1.log")
application = sdk.get_adxl_application()

# quickstart adxl stream
application.start_sensor()
application.subscribe_stream()
application.unsubscribe_stream()
application.stop_sensor()
```

This code example will place your watch into bootloader mode. If this code works, you can use Wavetool to re-update the firmware.

```
from adi_study_watch import SDK

sdk = SDK("COM4", logging_filename="SDK.log")
application = sdk.get_pm_application()
application.enter_boot_loader_mode()
```


Regards,
Anoop

**Comment by StopFxxkingCoding** [comment]
Hi Anoop,

The code blocks have been executed. The logging files are here:
- SDK1.log -  adxl reading
```
2021-09-07 22:26:03 - MainThread - adi_study_watch.sdk - DEBUG - ----- Study Watch SDK Started -----
2021-09-07 22:26:03 - MainThread - adi_study_watch.core.packet_manager - DEBUG - Packet ready : {'header': {'source': [199, 5], 'destination': [197, 0], 'length': [0, 21], 'checksum': [0, 0]}, 'payload': {'command': [66], 'status': [0], 'year': [229, 7], 'month': [9], 'day': [7], 'hour': [22], 'minute': [26], 'second': [3], 'tz_sec': [128, 112, 0, 0]}}
2021-09-07 22:26:03 - MainThread - adi_study_watch.core.packet_manager - INFO - TX :: 0xC7:0x05:0xC5:0x00:0x00:0x15:0x00:0x00:0x42:0x00:0xE5:0x07:0x09:0x07:0x16:0x1A:0x03:0x80:0x70:0x00:0x00
2021-09-07 22:26:03 - process_thread - adi_study_watch.core.packet_manager - INFO - RX::0xC5:0x00:0xC7:0x05:0x00:0x0A:0x00:0x00:0x43:0x00
2021-09-07 22:26:03 - MainThread - adi_study_watch.application.common_application - DEBUG - Packet decoded : {'header': {'source': <Application.PM: ['0xC5', '0x00']>, 'destination': <Application.APP_USB: ['0xC7', '0x05']>, 'length': '0xA', 'checksum': '0x0'}, 'payload': {'command': <PMCommand.SET_DATE_TIME_RES: ['0x43']>, 'status': <CommonStatus.OK: ['0x00']>}}
2021-09-07 22:26:03 - MainThread - adi_study_watch.core.packet_manager - DEBUG - Packet ready : {'header': {'source': [199, 5], 'destination': [193, 2], 'length': [0, 12], 'checksum': [0, 0]}, 'payload': {'command': [4], 'status': [0], 'stream_address': [0, 0]}}
2021-09-07 22:26:03 - MainThread - adi_study_watch.core.packet_manager - INFO - TX :: 0xC7:0x05:0xC1:0x02:0x00:0x0C:0x00:0x00:0x04:0x00:0x00:0x00
2021-09-07 22:26:03 - process_thread - adi_study_watch.core.packet_manager - INFO - RX::0xC1:0x02:0xC7:0x05:0x00:0x0C:0x00:0x00:0x05:0x02:0x00:0x00
2021-09-07 22:26:03 - MainThread - adi_study_watch.application.common_application - DEBUG - Packet decoded : {'header': {'source': <Application.ADXL: ['0xC1', '0x02']>, 'destination': <Application.APP_USB: ['0xC7', '0x05']>, 'length': '0xC', 'checksum': '0x0'}, 'payload': {'command': <CommonCommand.START_SENSOR_RES: ['0x05']>, 'status': <CommonStatus.STREAM_STARTED: ['0x02']>, 'stream_address': <Stream.NULL: ['0x00', '0x00']>}}
2021-09-07 22:26:03 - MainThread - adi_study_watch.core.packet_manager - DEBUG - Packet ready : {'header': {'source': [199, 5], 'destination': [193, 2], 'length': [0, 12], 'checksum': [0, 0]}, 'payload': {'command': [12], 'status': [0], 'stream_address': [2, 194]}}
2021-09-07 22:26:03 - MainThread - adi_study_watch.core.packet_manager - INFO - TX :: 0xC7:0x05:0xC1:0x02:0x00:0x0C:0x00:0x00:0x0C:0x00:0x02:0xC2
2021-09-07 22:26:03 - process_thread - adi_study_watch.core.packet_manager - INFO - RX::0xC1:0x02:0xC7:0x05:0x00:0x0C:0x00:0x00:0x0D:0x09:0x02:0xC2
2021-09-07 22:26:03 - MainThread - adi_study_watch.application.common_application - DEBUG - Packet decoded : {'header': {'source': <Application.ADXL: ['0xC1', '0x02']>, 'destination': <Application.APP_USB: ['0xC7', '0x05']>, 'length': '0xC', 'checksum': '0x0'}, 'payload': {'command': <CommonCommand.SUBSCRIBE_STREAM_RES: ['0x0D']>, 'status': <CommonStatus.SUBSCRIBER_ADDED: ['0x09']>, 'stream_address': <Stream.ADXL: ['0xC2', '0x02']>}}
2021-09-07 22:26:03 - MainThread - adi_study_watch.core.packet_manager - DEBUG - Packet ready : {'header': {'source': [199, 5], 'destination': [193, 2], 'length': [0, 12], 'checksum': [0, 0]}, 'payload': {'command': [14], 'status': [0], 'stream_address': [2, 194]}}
2021-09-07 22:26:03 - MainThread - adi_study_watch.core.packet_manager - INFO - TX :: 0xC7:0x05:0xC1:0x02:0x00:0x0C:0x00:0x00:0x0E:0x00:0x02:0xC2
2021-09-07 22:26:03 - process_thread - adi_study_watch.core.packet_manager - INFO - RX::0xC1:0x02:0xC7:0x05:0x00:0x0C:0x00:0x00:0x0F:0x0A:0x02:0xC2
2021-09-07 22:26:03 - MainThread - adi_study_watch.application.common_application - DEBUG - Packet decoded : {'header': {'source': <Application.ADXL: ['0xC1', '0x02']>, 'destination': <Application.APP_USB: ['0xC7', '0x05']>, 'length': '0xC', 'checksum': '0x0'}, 'payload': {'command': <CommonCommand.UNSUBSCRIBE_STREAM_RES: ['0x0F']>, 'status': <CommonStatus.SUBSCRIBER_REMOVED: ['0x0A']>, 'stream_address': <Stream.ADXL: ['0xC2', '0x02']>}}
2021-09-07 22:26:03 - MainThread - adi_study_watch.core.packet_manager - DEBUG - Packet ready : {'header': {'source': [199, 5], 'destination': [193, 2], 'length': [0, 12], 'checksum': [0, 0]}, 'payload': {'command': [6], 'status': [0], 'stream_address': [0, 0]}}
2021-09-07 22:26:03 - MainThread - adi_study_watch.core.packet_manager - INFO - TX :: 0xC7:0x05:0xC1:0x02:0x00:0x0C:0x00:0x00:0x06:0x00:0x00:0x00
2021-09-07 22:26:03 - process_thread - adi_study_watch.core.packet_manager - INFO - RX::0xC1:0x02:0xC7:0x05:0x00:0x0C:0x00:0x00:0x07:0x03:0x00:0x00
2021-09-07 22:26:03 - MainThread - adi_study_watch.application.common_application - DEBUG - Packet decoded : {'header': {'source': <Application.ADXL: ['0xC1', '0x02']>, 'destination': <Application.APP_USB: ['0xC7', '0x05']>, 'length': '0xC', 'checksum': '0x0'}, 'payload': {'command': <CommonCommand.STOP_SENSOR_RES: ['0x07']>, 'status': <CommonStatus.STREAM_STOPPED: ['0x03']>, 'stream_address': <Stream.NULL: ['0x00', '0x00']>}}
```

- SDK.log - enter bootloader mode
```
2021-09-07 22:27:06 - MainThread - adi_study_watch.sdk - DEBUG - ----- Study Watch SDK Started -----
2021-09-07 22:27:06 - MainThread - adi_study_watch.core.packet_manager - DEBUG - Packet ready : {'header': {'source': [199, 5], 'destination': [197, 0], 'length': [0, 21], 'checksum': [0, 0]}, 'payload': {'command': [66], 'status': [0], 'year': [229, 7], 'month': [9], 'day': [7], 'hour': [22], 'minute': [27], 'second': [6], 'tz_sec': [128, 112, 0, 0]}}
2021-09-07 22:27:06 - MainThread - adi_study_watch.core.packet_manager - INFO - TX :: 0xC7:0x05:0xC5:0x00:0x00:0x15:0x00:0x00:0x42:0x00:0xE5:0x07:0x09:0x07:0x16:0x1B:0x06:0x80:0x70:0x00:0x00
2021-09-07 22:27:06 - process_thread - adi_study_watch.core.packet_manager - INFO - RX::0xC5:0x00:0xC7:0x05:0x00:0x0A:0x00:0x00:0x43:0x00
2021-09-07 22:27:06 - MainThread - adi_study_watch.application.common_application - DEBUG - Packet decoded : {'header': {'source': <Application.PM: ['0xC5', '0x00']>, 'destination': <Application.APP_USB: ['0xC7', '0x05']>, 'length': '0xA', 'checksum': '0x0'}, 'payload': {'command': <PMCommand.SET_DATE_TIME_RES: ['0x43']>, 'status': <CommonStatus.OK: ['0x00']>}}
2021-09-07 22:27:06 - MainThread - adi_study_watch.core.packet_manager - DEBUG - Packet ready : {'header': {'source': [199, 5], 'destination': [197, 0], 'length': [0, 10], 'checksum': [0, 0]}, 'payload': {'command': [128], 'status': [0]}}
2021-09-07 22:27:06 - MainThread - adi_study_watch.core.packet_manager - INFO - TX :: 0xC7:0x05:0xC5:0x00:0x00:0x0A:0x00:0x00:0x80:0x00
```

When I tried to make the watch enter the bootloader mode via the SDK, the watch screen had no change. After that, I tried to connect the watch with WaveTool, but the problem remained the same, i.e., the connection failed.

Best
Max

**Comment by anoop-adi** [comment]
Hi Max,

Try to move your watch in bootloader mode using python SDK.

Then try nrfutil library(https://github.com/NordicSemiconductor/pc-nrfutil). It is a python library that can also flash the watch, an alternative for wavetool firmware upgrade.

Use the following command to upgrade the firmware: (Don't forget to put your watch in bootloader mode using python SDK)
`nrfutil dfu serial -pkg ADI_project.zip -p COM4`

you can find ADI_project.zip here: https://github.com/analogdevicesinc/study-watch-sdk/tree/main/firmware
and nrfutil  library here : https://pypi.org/project/nrfutil/

Regards,
Anoop

**Comment by StopFxxkingCoding** [comment]
Hi Anoop,

That sounds cool! However, I am not sure that the watch can enter the bootloader mode with the help of Python SDK. Did the logging file _SDK.log_ aforementioned before mean the watch had entered the bootloader mode?

Best
Max

**Comment by anoop-adi** [comment]
Hi Max,

The only way to tell if the watch is in bootloader mode is by checking on the screen, and the LOG file only tells that watch is responding to commands. 

You can try nrfutil and let me know your observations.

Regards,
Anoop

**Comment by StopFxxkingCoding** [comment]
Hi Anoop,

The watch screen still doesn't work normally after I run the SDK-based code trying to make it enter bootloader mode. The watch screen shows meaningless snow dots.

Here I tried two ways to execute the re-updating:
- The first way is: I use SDK code trying to set the watch to enter the bootloader mode. But the watch screen has no change. Then I run the command line `nrfutil dfu serial -pkg ADI_project.zip -p COM5`, the progress bar keeps at 0% for a while. Finally, the program ends and prints an error, the key info is: `pc_ble_driver_py.exceptions.NordicSemiException: Serial port could not be opened on COM5. Reason: None`. I think this may be because the port is occupied by the adi_study_watch SDK.
- Based on the result of the first way, the second way is: firstly, I run the adi_study_watch SDK code trying to set the watch into the bootloader mode, which is the same as the first way. Then, I terminate it and run the nrfutil command. The progress bar keeps at 0%, too. After the programs finish, the key info of the printed error is: `pc_ble_driver_py.exceptions.NordicSemiException: No ping response after opening COM port`. This may mean the communication doesn't really start.

Do you think the bootloader has some problem and needs to be updated? I don't know whether the bootloader update with Jlink is complex or not. If it is simple, how about updating it first and then reinstall the firmware?

Best,
Max

**Comment by anoop-adi** [comment]
Hi Max,

Do you have a Jlink or any similar device (https://www.segger.com/products/debug-probes/j-link/)? It looks like we need to update the bootloader.

Regards,
Anoop

**Comment by MaxandYuki** [comment]
Hi Anoop,

I have got one now. And what need I do next? If you have any large attachments, you might send them to my email (maxleizhao@gmail.com).

Best,
Max

**Comment by Bahaa1199732** [comment]
Dear MaxandYuki,
I have the same described problem with ADI study watch exactly. Everything that happened to your watch is happening to mine. I followed all suggested solutions in this discussion but none of them worked. Did you find a solution for the problem? Please help.
